version: '3'
services:
  db:
    build: .
    restart: always
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
  graphql:
    image: graphile/postgraphile
    command: -c postgres://aybee_postgraphile:xyz@db/aybee --schema=aybee_dashboard --default-role aybee_postgraphile --token aybee_dashboard.jwt_token --secret blablabla --cors
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
