version: '2'
services:
  db:
    build: .
    restart: always
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
  graphql:
    image: graphile/postgraphile
    command: -c postgres://aybee_postgraphile:xyz@db/aybee --schema=aybee_dashboard --default-role aybee_postgraphile --token aybee_dashboard.jwt_token --secret blablabla --cors --dynamic-json
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DB=aybee
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=senha
